services:
  app:
    build: .
    ports:
      -"4000:3000"
    environment:
      - DB_NAME: ${DB_NAME}
    depends_on:
      - db

  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD: ${DB_PASSWORD}